env:
  node: true
  es2021: true
  mocha: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "prettier"
  - "prettier/@typescript-eslint"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 12
  project: "tsconfig.json"
  sourceType: module
plugins:
  - "@typescript-eslint"
rules: {}
