env:
  node: true
  es2021: true
  mocha: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - "@typescript-eslint"
  - "eslint-plugin-tsdoc"
ignorePatterns:
  - "node_modules"
  - "out"
  - "**/*.json"
rules: {}
